### ISSUE TITLE
TypeError: Expected int32, got list containing Tensors of type '_Message' instead

### ISSUE THREAD

**Issue by MichaelGuarin0** [mangate/ConvNetSent#1]
python2 sentence_convnet_final.py --static True --random False
file data/processed/mr.p already exists
Traceback (most recent call last):
  File "sentence_convnet_final.py", line 101, in <module>
    evaluate_mr()
  File "sentence_convnet_final.py", line 42, in evaluate_mr
    evaluate(x, 2, 10)
  File "sentence_convnet_final.py", line 35, in evaluate
    cnn_model.build_model(embedding_dim, vocab_size, filter_sizes, num_filters, vector_length, num_classes, trainable)
  File "/home/michael/project_improve_document_classification/ConvNetSent/model.py", line 75, in build_model
    h_pool = tf.concat(3, pooled_outputs)
  File "/home/michael/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1061, in concat
    dtype=dtypes.int32).get_shape(
  File "/home/michael/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 611, in convert_to_tensor
    as_ref=False)
  File "/home/michael/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/michael/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/michael/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/michael/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 376, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/michael/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

using...
nvcc V8.0.61
tensorflow 1.3.0
python 2.7.13

**Comment by PatrickSchrML** [comment]
tf.concat has changed the order of parameters. Just change it to: tf.concat(pooled_outputs, 3)
